# @package _global_
dataset:
  _name_: markov
  l_seq: 100 # length of sequence
  n_alphabet: 3 # alphabet size
  n_samples: 20000
  val_split: 0.05
  __l_max: ${.l_seq}

task:
  _target_: tasks.tasks.LMTask
  tied: False
  rescale: False
  init: null
  loss: cross_entropy
